services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:head
    ports:
      - 127.0.0.1:8123:8123 # http-client
      - 127.0.0.1:9000:9000 # native-client
      - 127.0.0.1:9363:9363 # prometheus
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./clickhouse/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  prometheus-agent:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/config-agent.yml'
      - '--enable-feature=agent'
    volumes:
      - ./prometheus/:/etc/prometheus/

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/config.yml'
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
